### ISSUE TITLE
YAMNet error

### ISSUE THREAD

**Issue by ajporterfield** [ankane/onnxruntime-ruby#8]
I'm getting into the following error when trying to run a prediction using a converted yamnet tflite model.

_[E:onnxruntime:, sequential_executor.cc:494 ExecuteKernel] Non-zero status code returned while running Slice node. Name:'yamnet_frames/tf_op_layer_StridedSlice_2/StridedSlice_2;StatefulPartitionedCall/yamnet_frames/tf_op_layer_StridedSlice_2/StridedSlice_2' Status Message: slice.cc:197 FillVectorsFromInput Starts and axes shape mismatch_

I started by downloading the tflite model from the [TensorFlow Hub](https://tfhub.dev/google/lite-model/yamnet/tflite/1).  I then used tf2onnx to convert the model to onnx from Terminal.

    python -m tf2onnx.convert --tflite lite-model_yamnet_tflite_1.tflite --output yamnet.onnx

Here's the Ruby code that I used to invoke the model.  I've used this exact same sample array to run predictions in Node.js using the YAMNet TensorFlow.js model, so I'm expecting the same results here in Ruby/ONNX.

    model = OnnxRuntime::Model.new("yamnet.onnx")
    samples = [-0.000396728515625, 0, 0.000457763671875, 0.000457763671875, ...]
    model.predict({ "waveform" => samples })

This is the shape of the inputs

    [{:name=>"waveform", :type=>"tensor(float)", :shape=>[-1]}]

Do you have any thoughts as to why I'm getting this error returned?  Do you have any suggestions on how to resolve?  Thanks!

**Comment by ankane** [comment]
Hi @ajporterfield, can you try running it in Python?

```python
import onnxruntime as ort

ort_sess = ort.InferenceSession('yamnet.onnx')
output = ort_sess.run(None, {'waveform': samples})
```

It may be something with the exported model (and would be good to rule that out).

**Comment by ajporterfield** [comment]
Thanks for the reply @ankane.  I really appreciate your help.  I'm getting the same/similar error when running it in Python.

_[E:onnxruntime:, sequential_executor.cc:494 ExecuteKernel] Non-zero status code returned while running Slice node. Name:'yamnet_frames/tf_op_layer_StridedSlice_2/StridedSlice_2;StatefulPartitionedCall/yamnet_frames/tf_op_layer_StridedSlice_2/StridedSlice_2' Status Message: slice.cc:197 FillVectorsFromInput Starts and axes shape mismatch_

**Comment by ankane** [comment]
I'd try exporting the TF model instead of the TFLite one (it sounds like it's worked for others - https://github.com/onnx/tensorflow-onnx/issues/1743).

**Comment by ajporterfield** [comment]
Yes, I saw that too.  I am unable to get tf2onnx.convert to work for the TF model.

    python -m tf2onnx.convert --saved-model ./yamnet_1 --output yamnet.onnx

Outputs quite a few warnings/errors

```
runpy.py:126: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2023-04-18 14:52:55,693 - WARNING - ***IMPORTANT*** Installed protobuf is not cpp accelerated. Conversion will be extremely slow. See https://github.com/onnx/tensorflow-onnx/issues/1557
2023-04-18 14:52:55,694 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2023-04-18 14:53:00,666 - ERROR - Unable to load fingerprint when loading saved model.
Traceback (most recent call last):
  File "/Users/andrewporterfield/.pyenv/versions/3.10.11/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 1015, in load_partial
    fingerprint = fingerprinting.read_fingerprint(export_dir)
  File "/Users/andrewporterfield/.pyenv/versions/3.10.11/lib/python3.10/site-packages/tensorflow/python/saved_model/fingerprinting.py", line 172, in read_fingerprint
    raise FileNotFoundError(f"SavedModel Fingerprint Error: {e}") from None  # pylint: disable=raise-missing-from
FileNotFoundError: SavedModel Fingerprint Error: Could not read fingerprint from directory: ./yamnet_1
2023-04-18 14:53:00,686 - INFO - Signatures found in model: [serving_default].
2023-04-18 14:53:00,686 - WARNING - '--signature_def' not specified, using first signature: serving_default
Traceback (most recent call last):
  File "/Users/andrewporterfield/.pyenv/versions/3.10.11/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/andrewporterfield/.pyenv/versions/3.10.11/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/andrewporterfield/.pyenv/versions/3.10.11/lib/python3.10/site-packages/tf2onnx/convert.py", line 710, in <module>
    main()
  File "/Users/andrewporterfield/.pyenv/versions/3.10.11/lib/python3.10/site-packages/tf2onnx/convert.py", line 242, in main
    graph_def, inputs, outputs, initialized_tables, tensors_to_rename = tf_loader.from_saved_model(
  File "/Users/andrewporterfield/.pyenv/versions/3.10.11/lib/python3.10/site-packages/tf2onnx/tf_loader.py", line 611, in from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names,
  File "/Users/andrewporterfield/.pyenv/versions/3.10.11/lib/python3.10/site-packages/tf2onnx/tf_loader.py", line 573, in _from_saved_model_v2
    graph_captures = concrete_func.graph._captures  # pylint: disable=protected-access
AttributeError: 'FuncGraph' object has no attribute '_captures'. Did you mean: 'captures'?
```

**Comment by ankane** [comment]
I'm not sure about that error. Probably worth reporting to `tf2onnx` (could also see if they know about the original error - I think it may have something to do with the dynamic dimension).
